# Generated by Django 3.1.1 on 2020-09-20 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
