# Generated by Django 3.1.1 on 2020-09-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
